### ISSUE TITLE
日服2.30.2好像爆炸了

### ISSUE THREAD

**Issue by RakkaHokori** [Tsuasahi/FGOFPSUnlocker#2]
![Screenshot_2021-03-18-16-50-29-318_com aniplex fategrandorder](https://user-images.githubusercontent.com/53964405/111598705-73df5a00-880a-11eb-90ab-46478f3d5ac6.jpg)
本来也想自己动手 发现和图里对不上 小白傻了

**Comment by Tsuasahi** [comment]
它确实是炸力:( 用nishuoshenme大佬的libmain吧
[https://github.com/nishuoshenme/FGOFPSUnlocker/releases/tag/fgo](https://github.com/nishuoshenme/FGOFPSUnlocker/releases/tag/fgo)
